[package]
name = "sglang-rust-utils"
version = "0.1.0"
edition = "2021"

[workspace]

[lib]
name = "sglang_rust_utils"
crate-type = ["cdylib"]

[features]
default = ["extension-module"]
extension-module = ["pyo3/extension-module"]

[dependencies]
pyo3 = { version = "0.28.3", features = ["abi3-py38"] }
hex = "0.4"
ignore = "0.4"
rayon = "1.10"
sha2 = "0.10"
regex = "1.12.3"
jsonschema = "0.28"
serde_json = "1.0"

[profile.release]
lto = true
opt-level = 3
